# Gli array in Python

In [1]:
import numpy as np

In [2]:
np.random.rand(5)

array([0.79481652, 0.09489826, 0.75981595, 0.24937138, 0.88601959])

In [3]:
np.random.rand(5, 2)

array([[0.55356352, 0.77198625],
       [0.22451026, 0.67319496],
       [0.92305764, 0.28926895],
       [0.72354384, 0.3522484 ],
       [0.55551147, 0.24963835]])

In [4]:
np.random.rand(5, 4, 3)

array([[[0.39272509, 0.23549692, 0.31309266],
        [0.30964787, 0.90012558, 0.18011359],
        [0.84614829, 0.64451099, 0.76414343],
        [0.64538827, 0.2844449 , 0.635692  ]],

       [[0.64434447, 0.61533132, 0.62378221],
        [0.28988146, 0.83660986, 0.84970092],
        [0.24022779, 0.70832875, 0.93971991],
        [0.03034294, 0.80836636, 0.85317653]],

       [[0.72496762, 0.49088538, 0.9315055 ],
        [0.51076519, 0.90831166, 0.26473598],
        [0.90262812, 0.64208989, 0.68788532],
        [0.86760528, 0.87741301, 0.34216036]],

       [[0.15408561, 0.72247871, 0.65508962],
        [0.97296684, 0.01512152, 0.56641601],
        [0.60115873, 0.87087404, 0.86390158],
        [0.42261411, 0.4226599 , 0.17369891]],

       [[0.48205607, 0.3696417 , 0.6561241 ],
        [0.08516622, 0.53684659, 0.23141124],
        [0.42688404, 0.40272395, 0.25245578],
        [0.89182005, 0.38666837, 0.94299634]]])

In [5]:
np.random.rand(5, 4, 3, 2)

array([[[[0.2640355 , 0.47643659],
         [0.01148454, 0.8252748 ],
         [0.72722588, 0.38753076]],

        [[0.04892127, 0.30487329],
         [0.09723588, 0.62915314],
         [0.90503015, 0.24652008]],

        [[0.08060546, 0.02428663],
         [0.43027966, 0.78915981],
         [0.31705231, 0.22377848]],

        [[0.61717414, 0.00418052],
         [0.42431295, 0.04495836],
         [0.72617391, 0.0019094 ]]],


       [[[0.81347719, 0.66805256],
         [0.11628646, 0.03004765],
         [0.76682177, 0.70883376]],

        [[0.41905154, 0.86866671],
         [0.28241437, 0.97028552],
         [0.047238  , 0.93121784]],

        [[0.24577425, 0.3200433 ],
         [0.67696297, 0.51842291],
         [0.70995168, 0.65329426]],

        [[0.84647267, 0.2490196 ],
         [0.95586684, 0.51906868],
         [0.11657712, 0.27007504]]],


       [[[0.80272967, 0.97587661],
         [0.58152367, 0.28224014],
         [0.54064785, 0.48555419]],

        [[0.57204146, 0.51610286]

In [10]:
arr1 = np.random.rand(20)

In [11]:
arr1

array([0.86645499, 0.25670533, 0.20346663, 0.24356333, 0.23404393,
       0.39805512, 0.75868074, 0.83492659, 0.24124379, 0.85856442,
       0.88705235, 0.69728509, 0.80967541, 0.60027397, 0.11062803,
       0.81933385, 0.66194518, 0.30329307, 0.17864232, 0.18101703])

In [14]:
arr1.reshape(20, 1)

array([[0.86645499],
       [0.25670533],
       [0.20346663],
       [0.24356333],
       [0.23404393],
       [0.39805512],
       [0.75868074],
       [0.83492659],
       [0.24124379],
       [0.85856442],
       [0.88705235],
       [0.69728509],
       [0.80967541],
       [0.60027397],
       [0.11062803],
       [0.81933385],
       [0.66194518],
       [0.30329307],
       [0.17864232],
       [0.18101703]])

In [15]:
arr1.reshape(10, 2)

array([[0.86645499, 0.25670533],
       [0.20346663, 0.24356333],
       [0.23404393, 0.39805512],
       [0.75868074, 0.83492659],
       [0.24124379, 0.85856442],
       [0.88705235, 0.69728509],
       [0.80967541, 0.60027397],
       [0.11062803, 0.81933385],
       [0.66194518, 0.30329307],
       [0.17864232, 0.18101703]])

In [16]:
arr1.reshape(5, 4)

array([[0.86645499, 0.25670533, 0.20346663, 0.24356333],
       [0.23404393, 0.39805512, 0.75868074, 0.83492659],
       [0.24124379, 0.85856442, 0.88705235, 0.69728509],
       [0.80967541, 0.60027397, 0.11062803, 0.81933385],
       [0.66194518, 0.30329307, 0.17864232, 0.18101703]])

In [18]:
arr2 = arr1.reshape(5, 4)

In [19]:
arr2.shape

(5, 4)