In [1]:
import pandas as pd
import numpy as np
from keras.utils import np_utils
import keras
from keras.models import Sequential
from keras import layers
from keras.optimizers import SGD

from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

/Users/valentinaporcu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
# carichiamo i dati del dataset iris

In [3]:
df =  pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", header = 0)

In [4]:
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', "Class"]

In [5]:
df.head(5)

sepal_length  sepal_width  petal_length  petal_width        Class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [6]:
# dividiamo i dati dal fattore di classificazione

In [7]:
df, cl = (df.iloc[:, 0:4], df['Class'])

In [8]:
df.head(5)

sepal_length  sepal_width  petal_length  petal_width
0           4.9          3.0           1.4          0.2
1           4.7          3.2           1.3          0.2
2           4.6          3.1           1.5          0.2
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4

In [9]:
cl.head(5)

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Class, dtype: object

In [10]:
cl.value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        49
Name: Class, dtype: int64

In [11]:
set(cl)

{'Iris-setosa', 'Iris-versicolor', 'Iris-virginica'}

In [12]:
# normalizziamo il dataset

In [13]:
df_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
df1 = df_scaler.fit_transform(df)

In [14]:
df1.shape

(149, 4)

In [15]:
df1.dtype

dtype('float64')

In [16]:
cl1 = LabelEncoder().fit_transform(cl)

In [17]:
cl1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
# dividiamo in train set e test set

In [19]:
x_train, x_test, y_train, y_test = train_test_split(df1, cl1, test_size = 0.3)

In [20]:
x_train.shape

(104, 4)

In [21]:
y_train.shape

(104,)

In [22]:
x_test.shape

(45, 4)

In [23]:
y_test.shape

(45,)

In [24]:
# prepariamo il fattore di classificazione

In [25]:
y_train = np_utils.to_categorical(y_train, 3)
y_test = np_utils.to_categorical(y_test, 3)

In [26]:
# creiamo il modello neurale

In [27]:
model = Sequential()
model.add(layers.Dense(50, input_dim=x_train.shape[1], activation='relu'))
model.add(layers.Dense(40, activation='relu'))
model.add(layers.Dense(30, activation='relu'))
model.add(layers.Dense(25, activation='relu'))
model.add(layers.Dense(3, activation='softmax'))

In [28]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 50)                250       
_________________________________________________________________
dense_2 (Dense)              (None, 40)                2040      
_________________________________________________________________
dense_3 (Dense)              (None, 30)                1230      
_________________________________________________________________
dense_4 (Dense)              (None, 25)                775       
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 78        
Total params: 4,373
Trainable params: 4,373
Non-trainable params: 0
_________________________________________________________________


In [29]:
model.compile(loss='categorical_crossentropy',
              optimizer= 'adam',
              metrics=['accuracy'])

In [30]:
history = model.fit(x_train, y_train,
                    batch_size = 10, epochs = 50,
                    verbose = 1, validation_split = 0.3)

Train on 72 samples, validate on 32 samples
Epoch 1/50
72/72 [==============================] - 0s 3ms/step - loss: 1.1103 - acc: 0.2361 - val_loss: 1.0854 - val_acc: 0.7813
Epoch 2/50
72/72 [==============================] - 0s 202us/step - loss: 1.0797 - acc: 0.6528 - val_loss: 1.0670 - val_acc: 0.7500
Epoch 3/50
72/72 [==============================] - 0s 224us/step - loss: 1.0523 - acc: 0.7222 - val_loss: 1.0453 - val_acc: 0.5313
Epoch 4/50
72/72 [==============================] - 0s 215us/step - loss: 1.0212 - acc: 0.6806 - val_loss: 1.0145 - val_acc: 0.5313
Epoch 5/50
72/72 [==============================] - 0s 211us/step - loss: 0.9800 - acc: 0.6806 - val_loss: 0.9744 - val_acc: 0.5313
Epoch 6/50
72/72 [==============================] - 0s 215us/step - loss: 0.9239 - acc: 0.6806 - val_loss: 0.9158 - val_acc: 0.5313
Epoch 7/50
72/72 [==============================] - 0s 210us/step - loss: 0.8594 - acc: 0.6806 - val_loss: 0.8579 - val_acc: 0.5313
Epoch 8/50
72/72 [================

In [31]:
score = model.evaluate(x_test, y_test, verbose=1)

45/45 [==============================] - 0s 101us/step


In [32]:
score

[0.23405558069547017, 0.8888888915379842]

In [33]:
# carichiamo i dati del dataset PIMA

In [34]:
df = pd.read_csv('/Users/valentinaporcu/Desktop/pid.csv')

In [35]:
df.head(5)

Unnamed: 0  pregnant  glucose  pressure  triceps  insulin  mass  pedigree  \
0           1         6      148        72       35        0  33.6     0.627   
1           2         1       85        66       29        0  26.6     0.351   
2           3         8      183        64        0        0  23.3     0.672   
3           4         1       89        66       23       94  28.1     0.167   
4           5         0      137        40       35      168  43.1     2.288   

   age diabetes  
0   50      pos  
1   31      neg  
2   32      pos  
3   21      neg  
4   33      pos

In [36]:
df = df.drop(['Unnamed: 0'], axis=1)

In [37]:
df.head()

pregnant  glucose  pressure  triceps  insulin  mass  pedigree  age diabetes
0         6      148        72       35        0  33.6     0.627   50      pos
1         1       85        66       29        0  26.6     0.351   31      neg
2         8      183        64        0        0  23.3     0.672   32      pos
3         1       89        66       23       94  28.1     0.167   21      neg
4         0      137        40       35      168  43.1     2.288   33      pos

In [38]:
df.shape

(768, 9)

In [39]:
df, cl = (df.iloc[:, 0:8], df['diabetes'])

In [40]:
df.shape

(768, 8)

In [41]:
cl.shape

(768,)

In [42]:
df_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
df1 = df_scaler.fit_transform(df)

In [43]:
cl1 = LabelEncoder().fit_transform(cl)

In [44]:
x_train, x_test, y_train, y_test = train_test_split(df1, cl1, test_size = 0.3)

In [45]:
x_train.shape

(537, 8)

In [46]:
x_test.shape

(231, 8)

In [47]:
y_train.shape

(537,)

In [48]:
y_test.shape

(231,)

In [49]:
y_train = np_utils.to_categorical(y_train, 2)
y_test = np_utils.to_categorical(y_test, 2)

In [50]:
# creazione del modello

In [51]:
model1 = Sequential()
model1.add(layers.Dense(50, input_dim=x_train.shape[1], activation='relu'))
model1.add(layers.Dense(40, activation='relu'))
model1.add(layers.Dense(30, activation='relu'))
model1.add(layers.Dense(25, activation='relu'))
model1.add(layers.Dense(2, activation='sigmoid'))

model1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 50)                450       
_________________________________________________________________
dense_7 (Dense)              (None, 40)                2040      
_________________________________________________________________
dense_8 (Dense)              (None, 30)                1230      
_________________________________________________________________
dense_9 (Dense)              (None, 25)                775       
_________________________________________________________________
dense_10 (Dense)             (None, 2)                 52        
Total params: 4,547
Trainable params: 4,547
Non-trainable params: 0
_________________________________________________________________


In [52]:
model1.compile(loss='binary_crossentropy',
              optimizer= 'adam',
              metrics=['accuracy'])

history = model1.fit(x_train, y_train,
                    batch_size = 10, epochs = 50,
                    verbose = 1, validation_split = 0.3)

Train on 375 samples, validate on 162 samples
Epoch 1/50
375/375 [==============================] - 0s 784us/step - loss: 0.6897 - acc: 0.5560 - val_loss: 0.6695 - val_acc: 0.7284
Epoch 2/50
375/375 [==============================] - 0s 173us/step - loss: 0.6727 - acc: 0.6187 - val_loss: 0.6287 - val_acc: 0.7284
Epoch 3/50
375/375 [==============================] - 0s 173us/step - loss: 0.6560 - acc: 0.6267 - val_loss: 0.6055 - val_acc: 0.7253
Epoch 4/50
375/375 [==============================] - 0s 162us/step - loss: 0.6369 - acc: 0.6427 - val_loss: 0.5875 - val_acc: 0.7191
Epoch 5/50
375/375 [==============================] - 0s 161us/step - loss: 0.6162 - acc: 0.6973 - val_loss: 0.5691 - val_acc: 0.7191
Epoch 6/50
375/375 [==============================] - 0s 175us/step - loss: 0.6009 - acc: 0.6933 - val_loss: 0.5369 - val_acc: 0.7315
Epoch 7/50
375/375 [==============================] - 0s 167us/step - loss: 0.5987 - acc: 0.7027 - val_loss: 0.5526 - val_acc: 0.7099
Epoch 8/50
375/3

In [53]:
score1 = model1.evaluate(x_test, y_test, verbose=1)

score1

231/231 [==============================] - 0s 43us/step


[0.5483533484595162, 0.7510822513402798]

In [54]:
pred = model1.predict(x_test)

In [55]:
rounded = [np.round(x) for x in pred]

In [56]:
rounded

[array([1., 0.], dtype=float32),
 array([0., 1.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([0., 1.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([0., 1.], dtype=float32),
 array([1., 1.], dtype=float32),
 array([0., 1.], dtype=float32),
 array([0., 1.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([0., 1.], dtype=float32),
 array([0., 1.], dtype=float32),
 array([0., 1.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([0., 1.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([0., 1.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([0.